REDIS_HOST=redis
REDIS_PORT=6379

POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0-secure-password-change-me

ALLOW_ENABLE_WAIT_RESULT=true
ENABLE_WAIT_RESULT=true
CPU_TIME_LIMIT=5
MAX_CPU_TIME_LIMIT=15
WALL_TIME_LIMIT=10
MAX_WALL_TIME_LIMIT=20
MEMORY_LIMIT=128000
MAX_MEMORY_LIMIT=256000
MAX_FILE_SIZE=1024
ENABLE_NETWORK=false
